# Generated by Django 4.0.6 on 2022-07-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere_Licence',
            fields=[
                ('filiere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.filiere')),
            ],
            options={
                'verbose_name': 'Filière de licence',
                'verbose_name_plural': 'Filières de licence',
            },
            bases=('Inscrire.filiere',),
        ),
        migrations.CreateModel(
            name='Filiere_Master',
            fields=[
                ('filiere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.filiere')),
            ],
            options={
                'verbose_name': 'Filière de master',
                'verbose_name_plural': 'Filières de master',
            },
            bases=('Inscrire.filiere',),
        ),
    ]
