# Generated by Django 4.0.6 on 2022-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0003_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nni', models.IntegerField()),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('filiere', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Orinetation',
                'verbose_name_plural': 'Orientations',
            },
        ),
    ]
