# Generated by Django 4.0.6 on 2022-07-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0004_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photoEtudiant', models.ImageField(null=True, upload_to='')),
                ('nni', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('carteIdentite', models.ImageField(null=True, upload_to='')),
                ('numBac', models.IntegerField()),
                ('serie', models.CharField(max_length=200)),
                ('releveNote', models.ImageField(null=True, upload_to='')),
                ('session', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('pays', models.CharField(max_length=200)),
                ('AnObtantionBac', models.DateField()),
                ('niveau', models.CharField(max_length=200, null=True)),
                ('licence', models.CharField(max_length=200)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscrire.filiere_master')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant_Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photoEtudiant', models.ImageField(null=True, upload_to='')),
                ('nni', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('carteIdentite', models.ImageField(null=True, upload_to='')),
                ('numBac', models.IntegerField()),
                ('serie', models.CharField(max_length=200)),
                ('releveNote', models.ImageField(null=True, upload_to='')),
                ('session', models.CharField(max_length=200)),
                ('moyenGeneral', models.FloatField()),
                ('pays', models.CharField(max_length=200)),
                ('AnObtantionBac', models.DateField()),
                ('niveau', models.CharField(max_length=200, null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inscrire.filiere_licence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
