# Generated by Django 4.0.6 on 2022-07-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0005_etudiant_master_etudiant_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant_Prive_Licence',
            fields=[
                ('etudiant_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Prive_Master',
            fields=[
                ('etudiant_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_master',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Licence',
            fields=[
                ('etudiant_licence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_licence')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_licence',),
        ),
        migrations.CreateModel(
            name='Etudiant_Public_Master',
            fields=[
                ('etudiant_master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inscrire.etudiant_master')),
            ],
            options={
                'abstract': False,
            },
            bases=('Inscrire.etudiant_master',),
        ),
    ]
