# Generated by Django 4.1.3 on 2022-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscrire', '0008_alter_etudiant_prive_master_niveau1_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commantire', models.CharField(max_length=500)),
                ('fich', models.FileField(blank=True, upload_to='')),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
